# Generated by Django 5.1.4 on 2025-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='1e23691efaaf4', max_length=13, unique=True),
        ),
    ]
