# Generated by Django 5.1.4 on 2025-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='f547f9dc4fe74', max_length=13, unique=True),
        ),
    ]
