# Generated by Django 5.1.4 on 2025-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='8b98db3cb0954', max_length=13, unique=True),
        ),
    ]
