# Generated by Django 5.1.4 on 2025-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
