# Generated by Django 5.1.4 on 2025-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_records', '0003_borrowrecord_borrowed_at_alter_borrowrecord_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
